### ISSUE TITLE
Installation fails.

### ISSUE THREAD

**Issue by darkshifty** [vuefront/prestashop#2]
When you initially start with `yarn run dev` the following error is given:

` ERROR  Failed to compile with 224 errors                                                           friendly-errors 16:01:13                                                                                                                                These dependencies were not found:                                                                  friendly-errors 16:01:13                                                                                                      friendly-errors 16:01:13  * core-js/modules/es6.array.find in ./.nuxt/client.js                                               friendly-errors 16:01:13  * core-js/modules/es6.array.iterator in ./.nuxt/client.js                                           friendly-errors 16:01:13  * core-js/modules/es6.date.to-string in ./.nuxt/utils.js, ./.nuxt/components/nuxt.js and 1 other    friendly-errors 16:01:13  * core-js/modules/es6.function.name in ./.nuxt/client.js, ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vuefront/lib/components/molecules/product-option/select.vue?vue&type=script&lang=js& and 5 others                                                                                                                    * core-js/modules/es6.number.constructor in ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vuefront/lib/components/atoms/alert/alert.vue?vue&type=script&lang=js&, ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vuefront/lib/components/atoms/heading/heading.vue?vue&type=script&lang=js& and 14 others                                                                                      * core-js/modules/es6.object.assign in ./.nuxt/client.js                                            friendly-errors 16:01:13  * core-js/modules/es6.object.keys in ./.nuxt/client.js, ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vuefront/lib/components/extensions/account/account/account.vue?vue&type=script&lang=js& and 30 others                                                                                                                  * core-js/modules/es6.object.to-string in ./.nuxt/client.js, ./.nuxt/components/nuxt-link.client.js and 33 others             * core-js/modules/es6.promise in ./.nuxt/client.js                                                  friendly-errors 16:01:13  * core-js/modules/es6.regexp.constructor in ./.nuxt/utils.js, ./node_modules/vuefront/lib/utils/module.js                     * core-js/modules/es6.regexp.match in ./.nuxt/client.js                                             friendly-errors 16:01:13  * core-js/modules/es6.regexp.replace in ./.nuxt/utils.js, ./.nuxt/components/nuxt.js and 1 other    friendly-errors 16:01:13  * core-js/modules/es6.regexp.search in ./.nuxt/utils.js                                             friendly-errors 16:01:13  * core-js/modules/es6.regexp.split in ./.nuxt/utils.js, ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./.nuxt/components/nuxt-build-indicator.vue?vue&type=script&lang=js& and 4 others                       * core-js/modules/es6.regexp.to-string in ./.nuxt/utils.js, ./.nuxt/components/nuxt.js and 1 other  friendly-errors 16:01:13  * core-js/modules/es6.string.includes in ./.nuxt/client.js, ./.nuxt/components/nuxt-link.client.js  friendly-errors 16:01:13  * core-js/modules/es6.string.iterator in ./.nuxt/client.js, ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vuefront/lib/components/extensions/common/menu/menu.vue?vue&type=script&lang=js& and 1 other                                                                                                                       * core-js/modules/es6.string.repeat in ./.nuxt/utils.js                                             friendly-errors 16:01:13  * core-js/modules/es6.string.starts-with in ./.nuxt/utils.js                                        friendly-errors 16:01:13  * core-js/modules/es6.symbol in ./.nuxt/client.js, ./.nuxt/components/nuxt-link.client.js and 31 others                       * core-js/modules/es7.array.includes in ./.nuxt/client.js, ./.nuxt/components/nuxt-link.client.js   friendly-errors 16:01:13  * core-js/modules/es7.object.get-own-property-descriptors in ./.nuxt/index.js, ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vuefront/lib/components/extensions/account/account/account.vue?vue&type=script&lang=js& and 30 others                                                                                           * core-js/modules/es7.promise.finally in ./.nuxt/client.js                                          friendly-errors 16:01:13  * core-js/modules/es7.symbol.async-iterator in ./.nuxt/client.js, ./.nuxt/components/nuxt-link.client.js                      * core-js/modules/web.dom.iterable in ./.nuxt/client.js, ./.nuxt/components/nuxt-link.client.js and 32 others                                                                                                                     friendly-errors 16:01:13  To install them, you can run: npm install --save core-js/modules/es6.array.find core-js/modules/es6.array.iterator core-js/modules/es6.date.to-string core-js/modules/es6.function.name core-js/modules/es6.number.constructor core-js/modules/es6.object.assign core-js/modules/es6.object.keys core-js/modules/es6.object.to-string core-js/modules/es6.promise core-js/modules/es6.regexp.constructor core-js/modules/es6.regexp.match core-js/modules/es6.regexp.replace core-js/modules/es6.regexp.search core-js/modules/es6.regexp.split core-js/modules/es6.regexp.to-string core-js/modules/es6.string.includes core-js/modules/es6.string.iterator core-js/modules/es6.string.repeat core-js/modules/es6.string.starts-with core-js/modules/es6.symbol core-js/modules/es7.array.includes core-js/modules/es7.object.get-own-property-descriptors core-js/modules/es7.promise.finally core-js/modules/es7.symbol.async-iterator core-js/modules/web.dom.iterable                                                                      i Waiting for file changes                                                                                          16:01:13  i Memory usage: 554 MB (RSS: 745 MB)`

**Comment by darkshifty** [comment]
After running `npm install` on top of the installation nuxt was installed and working as expected.

**Comment by dmitriyzhuk** [comment]
The installation process requires to first run

```
yarn create vuefront-app
```

this command will setup an app and install all the dependencies. in your case it seems it broke at some point of time and didn't install the dependencies so when you correctly ran npm install - those dependencies were added. 

try it on a clean install and let me know if you see any error along the way.

**Comment by darkshifty** [comment]
Correct, I followed the required steps. Both on Ubuntu 18.04 and Windows 10 (clean install), both fail to fetch the Nuxt package. For me it is resolved with the NPM install after all required steps.
